apiVersion: v1
kind: Service
metadata:
  name: python-service
spec:
  selector:
    app: python-httpstat
  ports:
    - port: 80
      targetPort: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: python-prometheus-deployment
  labels:
    app: python-httpstat
spec:
  replicas: 1
  selector:
    matchLabels:
      app: python-httpstat
  template:
    metadata:
      labels:
        app: python-httpstat
    spec:
      containers:
      - name: python-prometheus-metrics
        image: asuprabhat/python_prometheus_metrics:latest
        ports:
        - containerPort: 80
